     version: '3.8'
     
     services:
       directus:
         image: directus/directus:11.5
         ports:
           - "8055:8055"
         volumes:
           - ./uploads:/directus/uploads
           - ./extensions:/directus/extensions
           - ./database:/directus/database
         environment:
           KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
           SECRET: 'abcdef123456789'

           ADMIN_EMAIL: 'admin@admin.com'
           ADMIN_PASSWORD: 'adminadmin'

           DB_CLIENT: 'sqlite3'
           DB_FILENAME: '/directus/database/data.db'

           WEBSOCKETS_ENABLED: 'true'

           CORS_ENABLED: 'true'
           CORS_ORIGIN: '*'
           CORS_METHODS: 'GET,POST,PATCH,DELETE,OPTIONS'
           CORS_ALLOWED_HEADERS: '*'
           CORS_EXPOSED_HEADERS: '*'
           CORS_CREDENTIALS: 'true'
           CORS_MAX_AGE: '86400'

           PUBLIC_URL: 'http://localhost:8055'

         restart: unless-stopped